apiVersion: v1
kind: PersistentVolume
metadata:
  name: kanboard-plugins-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/homes/services/kanboard/plugins
    server: filehost.ocf.berkeley.edu
    readOnly: false
